### ISSUE TITLE
EFI

### ISSUE THREAD

**Issue by Charly1000** [Wndstorms/Asus-Zenbook-UX390UA-UX390UAK-Hackintosh#1]
Hello.
Can you please upload your EFI or OpenCore folder?

**Comment by Wndstorms** [comment]
Sure thing. Uploading now.



发自我的iPhone


------------------ Original ------------------

**Comment by Charly1000** [comment]
thank you very much I will looking forward to it.

**Comment by Wndstorms** [comment]
> thank you very much I will looking forward to it.

Done. Enjoy!
